name: Java CI

on: 
  push:
    branches: 
      - '**'
    tags:
      - none  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Set up JDK 8.0
      uses: actions/setup-java@v4.1.0
      with:
        distribution: temurin
        java-version: 8.0
        cache: maven

    - name: Build with Maven
      run: mvn -B -s .mvn/settings.xml clean deploy
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
