name: Release to Maven Central

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: "Version tag (e.g. 1.234.5)"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Replace default version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "0.0.0-SNAPSHOT"
        replace: ${{ inputs.tag }}
        include: "*.*ml"
        regex: false        

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Push Git tag
      run: |
        git config --global user.name 'CI'
        git config --global user.email 'noreply@northdata.de'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git tag ${{ github.event.inputs.tag }}
        git push --tags

    - name: Set up Maven cache
      uses: actions/cache@v2.1.1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1.4.0
      with:
        gpg_private_key: ${{ secrets.gpg_private_key }}
        gpg_passphrase: ${{ secrets.gpg_passphrase }}
        nexus_username: ${{ secrets.SONATYPE_USERNAME }}
        nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: release

    - name: Publish HTML to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2.9.0
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        EXTERNAL_REPOSITORY: northdata/northdata.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: target/classes/html    

    - name: Replace release version with default
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: ${{ inputs.tag }}
        replace: "0.0.0-SNAPSHOT"
        include: "*.*ml"
        regex: false        

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

